#!/bin/bash

echo "⚔️  Forging the binary: rayscape..."

SOURCE_FILES="src/main.c src/player.c src/world.c src/ui.c src/combat.c src/npc.c"

clang $SOURCE_FILES \
-I./src \
-I/opt/homebrew/include \
-L/opt/homebrew/lib \
-lraylib \
-framework OpenGL \
-framework Cocoa \
-framework IOKit \
-framework CoreAudio \
-framework CoreVideo \
-Wall -std=c99 -Wno-missing-braces \
-o rayscape

if [ $? -eq 0 ]; then
    echo "✅ Build successful!"
    ./rayscape
else
    echo "❌ Build failed."
fi